// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoyaou7oJSceSpc38hNL3OSpq8XYm99SU',
    appId: '1:528207214120:web:808f5d115350211be1e71d',
    messagingSenderId: '528207214120',
    projectId: 'e-commerce-app-e88c7',
    authDomain: 'e-commerce-app-e88c7.firebaseapp.com',
    storageBucket: 'e-commerce-app-e88c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhHc_1-_8OyytnQUG1kdRf71qF1bSWKV8',
    appId: '1:528207214120:android:ab6fe33256843b67e1e71d',
    messagingSenderId: '528207214120',
    projectId: 'e-commerce-app-e88c7',
    storageBucket: 'e-commerce-app-e88c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpppw_V7NT4AbyhaWQP12389t6oAQfYdE',
    appId: '1:528207214120:ios:006e2c43f83799ede1e71d',
    messagingSenderId: '528207214120',
    projectId: 'e-commerce-app-e88c7',
    storageBucket: 'e-commerce-app-e88c7.appspot.com',
    iosClientId: '528207214120-m4h1pvmv8h98tsb59j4jaeeffvgt642o.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpppw_V7NT4AbyhaWQP12389t6oAQfYdE',
    appId: '1:528207214120:ios:006e2c43f83799ede1e71d',
    messagingSenderId: '528207214120',
    projectId: 'e-commerce-app-e88c7',
    storageBucket: 'e-commerce-app-e88c7.appspot.com',
    iosClientId: '528207214120-m4h1pvmv8h98tsb59j4jaeeffvgt642o.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
